// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var MaterialUi_Card = require("@jsiebern/bs-material-ui/src/MaterialUi_Card.bs.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var Core = require("@material-ui/core");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js");
var Utils$PoliticoReact = require("../utils/Utils.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");

function Login(Props) {
  var onSubmit = Props.onSubmit;
  var match = React.useState((function () {
          return "";
        }));
  var email = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var password = match$1[0];
  var renderTextField = function (handleInputChange, placeholder, value, dataTestId) {
    return Utils$PoliticoReact.addTestId(dataTestId, React.createElement(Core.TextField, MaterialUi_TextField.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function ($$event) {
                          return Curry._1(handleInputChange, $$event.target.value);
                        }), undefined, placeholder, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(value), undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)));
  };
  return React.createElement("div", undefined, React.createElement(Core.Card, MaterialUi_Card.makeProps(undefined, undefined, Caml_option.some(React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, undefined, Caml_option.some(Utils$PoliticoReact.addTestId("login-form", React.createElement("form", {
                                                          onSubmit: (function (evt) {
                                                              evt.preventDefault();
                                                              Curry._2(onSubmit, email, password);
                                                              return /* () */0;
                                                            })
                                                        }, renderTextField(match[1], "email", email, "login-email"), renderTextField(match$1[1], "password", password, "login-password"), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, /* Center */980392437, Caml_option.some(React.createElement(Core.Button, MaterialUi_Button.makeProps("Submit", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "submit", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, true, /* Row */4102650, undefined, /* Center */980392437, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))))), undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, true, /* Row */4102650, undefined, /* Center */980392437, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)));
}

var make = Login;

exports.make = make;
/* react Not a pure module */
