// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("bs-fetch/src/Fetch.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function login(email, password) {
  var payload = { };
  payload["email"] = email;
  payload["password"] = password;
  return fetch(process.env.REACT_APP_API_LINK + "/auth/signin", Fetch.RequestInit[/* make */0](/* Post */2, {
                      "Content-Type": "application/json"
                    }, Caml_option.some(JSON.stringify(payload)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                return prim.json();
              }));
}

exports.login = login;
/* No side effect */
