// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var React = require("react");
var ReactTestingLibrary = require("bs-react-testing-library/src/ReactTestingLibrary.bs.js");
var Greeting$PoliticoReact = require("../Greeting.js");

Jest.describe("<Greeting />", (function (param) {
        return Jest.test("renders gretting component ", (function (param) {
                      var result = ReactTestingLibrary.render(undefined, undefined, React.createElement(Greeting$PoliticoReact.make, { }));
                      return Jest.Expect[/* toEqual */12]("Edit the reason files. (.re)", Jest.Expect[/* expect */0](result.container.firstChild.innerHTML));
                    }));
      }));

/*  Not a pure module */
