// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function addTestId(testId, re) {
  return React.cloneElement(re, {
              "data-testid": testId
            });
}

function setDictKeyAndValuePair(dict, key, value) {
  dict[key] = value;
  return /* () */0;
}

exports.addTestId = addTestId;
exports.setDictKeyAndValuePair = setDictKeyAndValuePair;
/* react Not a pure module */
