// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Greeting(Props) {
  return React.createElement("div", undefined, "Edit the reason files. (.re)");
}

var make = Greeting;

exports.make = make;
/* react Not a pure module */
