// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Routes$PoliticoReact = require("./routes.js");

ReactDOMRe.renderToElementWithId(React.createElement(Routes$PoliticoReact.make, { }), "root");

/*  Not a pure module */
