// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Greeting$PoliticoReact = require("./Greeting.js");

ReactDOMRe.renderToElementWithId(React.createElement(Greeting$PoliticoReact.make, { }), "root");

/*  Not a pure module */
