// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Auth$PoliticoReact = require("../../actions/Auth.js");

function spyonfetch(param) {
  return (jest.spyOn(global, 'fetch').mockImplementation(() => Promise.resolve({
      json: () => Promise.resolve({}),
    })));
}

Jest.describe("Auth fns", (function (param) {
        beforeEach((function () {
                return spyonfetch(/* () */0);
              }));
        return Jest.test("test handles login functionality as expected", (function (param) {
                      Auth$PoliticoReact.login("tev@gmail", "pass");
                      ((
        expect(global.fetch).toHaveBeenCalled()
      ));
                      ((
                expect(global.fetch).toHaveBeenCalledWith(
                    "https://tevpolitico.herokuapp.com/api/v2/auth/signin",
                    {"body": "{\"email\":\"tev@gmail\",\"password\":\"pass\"}",
                    "headers": {"Content-Type": "application/json"},
                    "integrity": "", "method": "POST", "referrerPolicy": ""})

        ));
                      return Jest.pass;
                    }));
      }));

exports.spyonfetch = spyonfetch;
/*  Not a pure module */
